# -*- coding: utf-8 -*-
"""scanpath.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UsRdIVE5Ax0vTbY67nHH80HWqPQrliDQ
"""

# http://pytorch.org/
from os import path
from wheel.pep425tags import get_abbr_impl, get_impl_ver, get_abi_tag
platform = '{}{}-{}'.format(get_abbr_impl(), get_impl_ver(), get_abi_tag())

accelerator = 'cu80' if path.exists('/opt/bin/nvidia-smi') else 'cpu'

!pip install -q http://download.pytorch.org/whl/{accelerator}/torch-0.3.0.post4-{platform}-linux_x86_64.whl torchvision
import torch

!git clone https://github.com/danenigma/Scanpath-Research-Project.git

cd Scanpath-Research-Project/data/

!curl --header 'Host: dl.dropboxusercontent.com' --user-agent 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0' --header 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' --header 'Accept-Language: en-US,en;q=0.5' --referer 'https://www.dropbox.com/' --cookie 'uc_session=WsTBkx44T9flRoIlebUlmlatCciwd6DEgbQqwkheIVcscrZhZanKGQvcvbjCXAej' --header 'Upgrade-Insecure-Requests: 1' 'https://dl.dropboxusercontent.com/content_link/BoGythNKNiDSUP6gKBzk3LyIrHteHElb1BdRlkuGN5UNQhW2vbu9LwpDtDJdxI5A/file?dl=1' --output 'MIT1003.tar'

!tar -xvf MIT1003.tar

cd ../

!git pull

!python train.py --num_epochs 50 --log_step 8

!python sample.py --image "png/test.jpeg"

from google.colab import files
files.download('png/test.npy')